# Generated by Django 5.1.4 on 2025-01-25 11:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='مبلغ را به ریال و بدون استفاده از کاما وارد کنید.', verbose_name='مبلغ خدمات')),
            ],
            options={
                'verbose_name': 'مبلغ خدمات',
                'verbose_name_plural': 'مبالغ خدمات',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(help_text='1 به معنای تراکنش موفق است', verbose_name='وضعیت')),
                ('amount', models.CharField(max_length=20, verbose_name='مبلغ به ریال')),
                ('transId', models.CharField(max_length=20, verbose_name='شماره تراکنش')),
                ('factorNumber', models.CharField(help_text='همان شناسه نوبت یا مشاوره است', max_length=20, verbose_name='شماره فاکتور')),
                ('mobile', models.CharField(max_length=10, verbose_name='شماره موبایل')),
                ('description', models.TextField(verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'تراکنش',
                'verbose_name_plural': 'تراکنش ها',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('1', 'از روی الگو'), ('2', 'خارج از الگو')], max_length=1, verbose_name='روش ایجاد')),
                ('date', models.CharField(max_length=10, verbose_name='تاریخ نوبت')),
                ('start_time', models.TimeField(default=django.utils.timezone.now, verbose_name='ساعت شروع')),
                ('status', models.CharField(choices=[('آزاد', 'آزاد'), ('رزرو شده', 'رزرو شده'), ('تکمیل شده', 'تکمیل شده')], default='آزاد', max_length=20, verbose_name='وضعیت نوبت')),
                ('cancle', models.BooleanField(default=False, verbose_name='اجازه کنسل')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_appointment', to=settings.AUTH_USER_MODEL, verbose_name='دکتر')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_appointment', to=settings.AUTH_USER_MODEL, verbose_name='بیمار')),
            ],
            options={
                'verbose_name': 'نوبت',
                'verbose_name_plural': 'نوبت ها',
            },
        ),
        migrations.CreateModel(
            name='AppointmentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.CharField(default='5', max_length=1, verbose_name='ستاره')),
                ('content', models.CharField(max_length=800, verbose_name='متن نظر')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ')),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appointment.appointment', verbose_name='نوبت')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('1', 'از روی الگو'), ('2', 'خارج از الگو')], default='2', max_length=1, verbose_name='روش ایجاد')),
                ('date', models.CharField(max_length=10, verbose_name='تاریخ مشاوره')),
                ('start_time', models.TimeField(default=django.utils.timezone.now, verbose_name='ساعت شروع')),
                ('end_time', models.TimeField(default=django.utils.timezone.now, verbose_name='ساعت پایان')),
                ('status', models.CharField(choices=[('آزاد', 'آزاد'), ('رزرو شده', 'رزرو شده'), ('تکمیل شده', 'تکمیل شده')], default='آزاد', max_length=20, verbose_name='وضعیت مشاوره')),
                ('allowed', models.BooleanField(default=False, verbose_name='اجازه چت')),
                ('cancle', models.BooleanField(default=False, verbose_name='اجازه کنسل')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_consultation', to=settings.AUTH_USER_MODEL, verbose_name='دکتر')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_consultation', to=settings.AUTH_USER_MODEL, verbose_name='بیمار')),
            ],
            options={
                'verbose_name': 'مشاوره',
                'verbose_name_plural': 'مشاوره ها',
            },
        ),
        migrations.CreateModel(
            name='ConsultationComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.CharField(default='5', max_length=1, verbose_name='ستاره')),
                ('content', models.CharField(max_length=800, verbose_name='متن نظر')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ')),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appointment.consultation', verbose_name='مشاوره')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن پیام')),
                ('file', models.FileField(blank=True, null=True, upload_to='message_files/', verbose_name='فایل ضمیمه')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ارسال')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_message', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('consultation', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='consultation_message', to='appointment.consultation', verbose_name='مشاوره')),
            ],
            options={
                'verbose_name': 'پیام',
                'verbose_name_plural': 'پیام ها',
            },
        ),
        migrations.CreateModel(
            name='TemplateAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('0', 'روز های شنبه'), ('1', 'روز های یک شنبه'), ('2', 'روز های دو شنبه'), ('3', 'روز های سه شنبه'), ('4', 'روز های چهار شنبه'), ('5', 'روز های پنج شنبه'), ('6', 'روز های جمعه')], max_length=30, verbose_name='روز هفته')),
                ('start_time', models.TimeField(default=django.utils.timezone.now, verbose_name='ساعت شروع')),
                ('end_time', models.TimeField(default=django.utils.timezone.now, verbose_name='ساعت پایان')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='td', to=settings.AUTH_USER_MODEL, verbose_name='دکتر')),
            ],
            options={
                'verbose_name': 'الگو نوبت دهی',
                'verbose_name_plural': 'الگو های نوبت دهی',
            },
        ),
    ]
