# Generated by Django 5.1.4 on 2025-01-25 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان درباره ما')),
                ('content', models.TextField(verbose_name='محتوای درباره ما')),
            ],
            options={
                'verbose_name': 'درباره ما',
                'verbose_name_plural': 'درباره ما',
            },
        ),
        migrations.CreateModel(
            name='AppointmentCancellationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=500, verbose_name='ماده')),
            ],
            options={
                'verbose_name': 'قانون لغو نوبت یا مشاوره',
                'verbose_name_plural': 'قوانین لغو نوبت یا مشاوره',
            },
        ),
        migrations.CreateModel(
            name='ComprehensiveRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=500, verbose_name='ماده')),
            ],
            options={
                'verbose_name': 'قانون جامع',
                'verbose_name_plural': 'قوانین جامع',
            },
        ),
        migrations.CreateModel(
            name='DemonstrationComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='نام و نام خانوادگی')),
                ('comment', models.TextField(verbose_name='محتوای نظر')),
            ],
            options={
                'verbose_name': 'نظر نمایشی',
                'verbose_name_plural': 'نظرات نمایشی',
            },
        ),
        migrations.CreateModel(
            name='DoctorRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=500, verbose_name='ماده')),
            ],
            options={
                'verbose_name': 'قانون دکترها',
                'verbose_name_plural': 'قوانین دکترها',
            },
        ),
        migrations.CreateModel(
            name='PatientRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=500, verbose_name='ماده')),
            ],
            options={
                'verbose_name': 'قانون بیماران',
                'verbose_name_plural': 'قوانین بیماران',
            },
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience', models.CharField(choices=[('بیمار', 'بیمار'), ('دکتر', 'دکتر')], max_length=20, verbose_name='سوال برای')),
                ('question', models.TextField(verbose_name='سوال')),
                ('answer', models.TextField(verbose_name='پاسخ')),
            ],
            options={
                'verbose_name': 'سوال متداول',
                'verbose_name_plural': 'سوالات متداول',
            },
        ),
        migrations.CreateModel(
            name='ParagraphAppointmentCancellationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='پاراگراف قانون')),
                ('appointment_cancellation_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacr', to='CMS.appointmentcancellationrule')),
            ],
            options={
                'verbose_name': 'پاراگراف قانون لغو نوبت یا مشاوره',
                'verbose_name_plural': 'پاراگراف های قوانین لغو نوبت یا مشاوره',
            },
        ),
        migrations.CreateModel(
            name='ParagraphComprehensiveRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='پاراگراف قانون')),
                ('comprehensive_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pcr', to='CMS.comprehensiverule')),
            ],
            options={
                'verbose_name': 'پاراگراف قانون جامع',
                'verbose_name_plural': 'پاراگراف های قوانین جامع',
            },
        ),
        migrations.CreateModel(
            name='ParagraphDoctorRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='پاراگراف قانون')),
                ('doctor_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdr', to='CMS.doctorrule')),
            ],
            options={
                'verbose_name': 'پاراگراف قانون دکترها',
                'verbose_name_plural': 'پاراگراف های قوانین دکترها',
            },
        ),
        migrations.CreateModel(
            name='ParagraphPatientRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='پاراگراف قانون')),
                ('patient_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ppr', to='CMS.patientrule')),
            ],
            options={
                'verbose_name': 'پاراگراف قانون بیماران',
                'verbose_name_plural': 'پاراگراف های قوانین بیماران',
            },
        ),
    ]
